import type {
  User,
  Application,
  Document,
  Appointment,
  Payment,
  Notification,
  CaseAssignment,
  CaseNote,
  AuditLog,
  Article,
  FAQ,
  ApplicationStatusHistory,
} from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    email: "priya.sharma@email.com",
    firstName: "Priya",
    lastName: "Sharma",
    role: "applicant",
    status: "active",
    mfaEnabled: false,
    createdAt: "2024-01-10T09:00:00Z",
    lastLogin: "2024-06-20T14:30:00Z",
  },
  {
    id: "u2",
    email: "carlos.ruiz@email.com",
    firstName: "Carlos",
    lastName: "Ruiz",
    role: "applicant",
    status: "active",
    mfaEnabled: true,
    createdAt: "2024-02-15T10:00:00Z",
    lastLogin: "2024-06-19T08:15:00Z",
  },
  {
    id: "o1",
    email: "anna.weber@avensaoverseas.com",
    firstName: "Anna",
    lastName: "Weber",
    role: "case_officer",
    status: "active",
    mfaEnabled: true,
    createdAt: "2023-06-01T09:00:00Z",
    lastLogin: "2024-06-20T09:00:00Z",
  },
  {
    id: "a1",
    email: "admin@avensaoverseas.com",
    firstName: "System",
    lastName: "Admin",
    role: "super_admin",
    status: "active",
    mfaEnabled: true,
    createdAt: "2023-01-01T00:00:00Z",
    lastLogin: "2024-06-20T07:00:00Z",
  },
  {
    id: "u3",
    email: "ahmed.ali@email.com",
    firstName: "Ahmed",
    lastName: "Ali",
    role: "applicant",
    status: "active",
    mfaEnabled: false,
    createdAt: "2024-03-05T11:00:00Z",
    lastLogin: "2024-06-18T16:45:00Z",
  },
  {
    id: "u4",
    email: "nina.kowalski@email.com",
    firstName: "Nina",
    lastName: "Kowalski",
    role: "applicant",
    status: "active",
    mfaEnabled: false,
    createdAt: "2024-04-12T08:00:00Z",
    lastLogin: "2024-06-17T13:20:00Z",
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-001",
    applicantId: "u1",
    routeId: "de-skilled-worker",
    countryId: "de",
    status: "document_review",
    currentStep: 8,
    referenceNumber: "AO-LK2X1A-R7P9",
    personalDetails: {
      firstName: "Priya",
      lastName: "Sharma",
      dateOfBirth: "1990-05-15",
      nationality: "Indian",
      passportNumber: "N1234567",
      passportExpiry: "2028-05-14",
      email: "priya.sharma@email.com",
      phone: "+91 98765 43210",
      address: "123 MG Road",
      city: "Bangalore",
      country: "India",
      postalCode: "560001",
    },
    educationEmployment: {
      highestEducation: "master",
      fieldOfStudy: "Computer Science",
      institution: "IIT Bangalore",
      graduationYear: "2014",
      occupation: "Software Engineer",
      currentEmployer: "TechCorp India",
      yearsExperience: 10,
      hasJobOffer: true,
      jobOfferEmployer: "Berlin Tech GmbH",
      jobOfferPosition: "Senior Software Engineer",
      annualSalary: 65000,
      currency: "EUR",
    },
    familyInfo: {
      maritalStatus: "married",
      spouseName: "Rahul Sharma",
      spouseNationality: "Indian",
      dependents: [],
    },
    financialInfo: {
      monthlyIncome: 5417,
      currency: "EUR",
      bankBalance: 25000,
      sponsorshipAvailable: false,
    },
    travelHistory: {
      previousVisaRejections: false,
      previousSchengenStays: [],
      currentResidenceStatus: "Long-term resident",
    },
    ruleSnapshot: JSON.stringify({ version: "2024.1", effectiveFrom: "2024-01-01" }),
    submittedAt: "2024-06-01T10:00:00Z",
    createdAt: "2024-05-20T09:00:00Z",
    updatedAt: "2024-06-15T14:00:00Z",
    assignedOfficerId: "o1",
  },
  {
    id: "app-002",
    applicantId: "u2",
    routeId: "nl-highly-skilled",
    countryId: "nl",
    status: "approved",
    currentStep: 10,
    referenceNumber: "AO-MN3Y2B-S8Q0",
    personalDetails: {
      firstName: "Carlos",
      lastName: "Ruiz",
      dateOfBirth: "1988-11-20",
      nationality: "Brazilian",
      passportNumber: "ZX9876543",
      passportExpiry: "2027-11-19",
      email: "carlos.ruiz@email.com",
      phone: "+55 11 99876 5432",
      address: "Rua das Flores, 45",
      city: "São Paulo",
      country: "Brazil",
      postalCode: "01310-100",
    },
    educationEmployment: {
      highestEducation: "master",
      fieldOfStudy: "Data Science",
      institution: "University of São Paulo",
      graduationYear: "2012",
      occupation: "Data Scientist",
      yearsExperience: 12,
      hasJobOffer: true,
      jobOfferEmployer: "DataCo Amsterdam BV",
      jobOfferPosition: "Lead Data Scientist",
      annualSalary: 82000,
      currency: "EUR",
    },
    ruleSnapshot: JSON.stringify({ version: "2024.1", effectiveFrom: "2024-01-01" }),
    submittedAt: "2024-03-10T12:00:00Z",
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-05-20T16:00:00Z",
    assignedOfficerId: "o1",
  },
  {
    id: "app-003",
    applicantId: "u3",
    routeId: "de-eu-blue-card",
    countryId: "de",
    status: "submitted",
    currentStep: 9,
    referenceNumber: "AO-OP4Z3C-T9R1",
    personalDetails: {
      firstName: "Ahmed",
      lastName: "Ali",
      dateOfBirth: "1992-08-10",
      nationality: "Egyptian",
      passportNumber: "A12345678",
      passportExpiry: "2026-08-09",
      email: "ahmed.ali@email.com",
      phone: "+20 100 123 4567",
      address: "15 Tahrir Square",
      city: "Cairo",
      country: "Egypt",
      postalCode: "11511",
    },
    educationEmployment: {
      highestEducation: "bachelor",
      fieldOfStudy: "Electrical Engineering",
      institution: "Cairo University",
      graduationYear: "2015",
      occupation: "Electrical Engineer",
      yearsExperience: 9,
      hasJobOffer: true,
      jobOfferEmployer: "EngineerPlus GmbH",
      jobOfferPosition: "Senior Electrical Engineer",
      annualSalary: 58000,
      currency: "EUR",
    },
    ruleSnapshot: JSON.stringify({ version: "2024.1", effectiveFrom: "2024-01-01" }),
    submittedAt: "2024-06-18T09:00:00Z",
    createdAt: "2024-06-10T08:00:00Z",
    updatedAt: "2024-06-18T09:00:00Z",
  },
];

export const MOCK_STATUS_HISTORY: ApplicationStatusHistory[] = [
  {
    id: "sh-001",
    applicationId: "app-001",
    status: "draft",
    actor: "Priya Sharma",
    actorRole: "applicant",
    timestamp: "2024-05-20T09:00:00Z",
    note: "Application created",
  },
  {
    id: "sh-002",
    applicationId: "app-001",
    status: "submitted",
    actor: "Priya Sharma",
    actorRole: "applicant",
    timestamp: "2024-06-01T10:00:00Z",
    note: "Application submitted for review",
  },
  {
    id: "sh-003",
    applicationId: "app-001",
    status: "document_review",
    actor: "Anna Weber",
    actorRole: "case_officer",
    timestamp: "2024-06-05T11:00:00Z",
    note: "Documents under review by case officer",
  },
  {
    id: "sh-004",
    applicationId: "app-002",
    status: "draft",
    actor: "Carlos Ruiz",
    actorRole: "applicant",
    timestamp: "2024-03-01T10:00:00Z",
  },
  {
    id: "sh-005",
    applicationId: "app-002",
    status: "submitted",
    actor: "Carlos Ruiz",
    actorRole: "applicant",
    timestamp: "2024-03-10T12:00:00Z",
  },
  {
    id: "sh-006",
    applicationId: "app-002",
    status: "document_review",
    actor: "Anna Weber",
    actorRole: "case_officer",
    timestamp: "2024-03-15T09:00:00Z",
  },
  {
    id: "sh-007",
    applicationId: "app-002",
    status: "under_review",
    actor: "Anna Weber",
    actorRole: "case_officer",
    timestamp: "2024-04-01T10:00:00Z",
  },
  {
    id: "sh-008",
    applicationId: "app-002",
    status: "approved",
    actor: "Anna Weber",
    actorRole: "case_officer",
    timestamp: "2024-05-20T16:00:00Z",
    note: "Application approved. Visa granted.",
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-001",
    applicationId: "app-001",
    applicantId: "u1",
    type: "passport",
    name: "Passport",
    fileName: "passport_priya_sharma.pdf",
    fileSize: 2048000,
    mimeType: "application/pdf",
    storageKey: "documents/u1/app-001/passport.pdf",
    status: "accepted",
    expiryDate: "2028-05-14",
    uploadedAt: "2024-06-01T10:30:00Z",
    reviewedAt: "2024-06-05T11:00:00Z",
    reviewedById: "o1",
  },
  {
    id: "doc-002",
    applicationId: "app-001",
    applicantId: "u1",
    type: "degree",
    name: "Master's Degree Certificate",
    fileName: "mtech_iit_priya.pdf",
    fileSize: 1536000,
    mimeType: "application/pdf",
    storageKey: "documents/u1/app-001/degree.pdf",
    status: "accepted",
    uploadedAt: "2024-06-01T10:45:00Z",
    reviewedAt: "2024-06-05T11:30:00Z",
    reviewedById: "o1",
  },
  {
    id: "doc-003",
    applicationId: "app-001",
    applicantId: "u1",
    type: "employment_contract",
    name: "Employment Contract – Berlin Tech GmbH",
    fileName: "employment_contract_berlin_tech.pdf",
    fileSize: 512000,
    mimeType: "application/pdf",
    storageKey: "documents/u1/app-001/contract.pdf",
    status: "under_review",
    uploadedAt: "2024-06-01T11:00:00Z",
  },
  {
    id: "doc-004",
    applicationId: "app-001",
    applicantId: "u1",
    type: "insurance",
    name: "Health Insurance Certificate",
    fileName: "health_insurance.pdf",
    fileSize: 256000,
    mimeType: "application/pdf",
    storageKey: "documents/u1/app-001/insurance.pdf",
    status: "required",
    uploadedAt: "2024-06-10T09:00:00Z",
  },
  {
    id: "doc-005",
    applicationId: "app-001",
    applicantId: "u1",
    type: "photo",
    name: "Biometric Photo",
    fileName: "biometric_photo.jpg",
    fileSize: 204800,
    mimeType: "image/jpeg",
    storageKey: "documents/u1/app-001/photo.jpg",
    status: "rejected",
    uploadedAt: "2024-06-01T11:15:00Z",
    reviewedAt: "2024-06-05T12:00:00Z",
    reviewedById: "o1",
    rejectionReason: "Photo background must be plain white. Please resubmit.",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "apt-001",
    applicationId: "app-001",
    applicantId: "u1",
    type: "biometrics",
    location: "German Consulate General, Mumbai",
    address: "Hoechst House, 10th Floor, Nariman Point, Mumbai 400021",
    date: "2024-07-15",
    time: "10:30",
    duration: 30,
    status: "scheduled",
    confirmationCode: "BIO-APT-2024-001",
    reminderSent: false,
    createdAt: "2024-06-10T14:00:00Z",
  },
  {
    id: "apt-002",
    applicationId: "app-002",
    applicantId: "u2",
    type: "document_submission",
    location: "Netherlands Consulate, São Paulo",
    address: "Av. Paulista, 2300 – 4° Andar, São Paulo, SP 01310-300",
    date: "2024-04-05",
    time: "14:00",
    duration: 45,
    status: "completed",
    confirmationCode: "DOC-APT-2024-002",
    reminderSent: true,
    createdAt: "2024-03-20T10:00:00Z",
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay-001",
    applicationId: "app-001",
    applicantId: "u1",
    type: "government_fee",
    amount: 75,
    currency: "EUR",
    status: "succeeded",
    transactionId: "TXN-2024-001234",
    provider: "Stripe",
    invoiceNumber: "INV-2024-001",
    description: "Germany Skilled Worker Visa – Government Application Fee",
    createdAt: "2024-06-01T10:00:00Z",
    completedAt: "2024-06-01T10:02:00Z",
    idempotencyKey: "app-001-gov-fee-001",
  },
  {
    id: "pay-002",
    applicationId: "app-001",
    applicantId: "u1",
    type: "service_fee",
    amount: 199,
    currency: "EUR",
    status: "succeeded",
    transactionId: "TXN-2024-001235",
    provider: "Stripe",
    invoiceNumber: "INV-2024-002",
    description: "Avensa Overseas Service Fee",
    createdAt: "2024-06-01T10:05:00Z",
    completedAt: "2024-06-01T10:06:00Z",
    idempotencyKey: "app-001-svc-fee-001",
  },
  {
    id: "pay-003",
    applicationId: "app-002",
    applicantId: "u2",
    type: "government_fee",
    amount: 285,
    currency: "EUR",
    status: "succeeded",
    transactionId: "TXN-2024-002001",
    provider: "Stripe",
    invoiceNumber: "INV-2024-003",
    description: "Netherlands HSM – IND Application Fee",
    createdAt: "2024-03-10T12:00:00Z",
    completedAt: "2024-03-10T12:01:00Z",
    idempotencyKey: "app-002-gov-fee-001",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    userId: "u1",
    type: "document_rejected",
    channel: "in_app",
    title: "Document Requires Resubmission",
    message:
      "Your biometric photo has been rejected. Please upload a new photo with a plain white background.",
    read: false,
    actionUrl: "/dashboard/documents",
    createdAt: "2024-06-05T12:05:00Z",
  },
  {
    id: "notif-002",
    userId: "u1",
    type: "appointment_booked",
    channel: "in_app",
    title: "Appointment Confirmed",
    message:
      "Your biometrics appointment at German Consulate General, Mumbai is confirmed for 15 July 2024 at 10:30 AM.",
    read: false,
    actionUrl: "/dashboard/appointments",
    createdAt: "2024-06-10T14:01:00Z",
  },
  {
    id: "notif-003",
    userId: "u1",
    type: "status_changed",
    channel: "in_app",
    title: "Application Status Updated",
    message: "Your application AO-LK2X1A-R7P9 has moved to Document Review.",
    read: true,
    actionUrl: "/dashboard/applications/app-001",
    createdAt: "2024-06-05T11:01:00Z",
    readAt: "2024-06-05T15:00:00Z",
  },
  {
    id: "notif-004",
    userId: "u1",
    type: "document_accepted",
    channel: "in_app",
    title: "Document Accepted",
    message: "Your passport has been reviewed and accepted.",
    read: true,
    actionUrl: "/dashboard/documents",
    createdAt: "2024-06-05T11:30:00Z",
    readAt: "2024-06-05T15:00:00Z",
  },
  {
    id: "notif-005",
    userId: "u1",
    type: "general",
    channel: "in_app",
    title: "Welcome to Avensa Overseas",
    message:
      "Your account has been created. Start by checking your EU immigration eligibility.",
    read: true,
    actionUrl: "/eligibility",
    createdAt: "2024-01-10T09:01:00Z",
    readAt: "2024-01-10T09:10:00Z",
  },
];

export const MOCK_CASE_ASSIGNMENTS: CaseAssignment[] = [
  {
    id: "ca-001",
    applicationId: "app-001",
    officerId: "o1",
    officerName: "Anna Weber",
    queue: "Germany Work Permits",
    priority: "high",
    assignedAt: "2024-06-05T10:00:00Z",
    dueDate: "2024-06-20T17:00:00Z",
    status: "active",
  },
  {
    id: "ca-002",
    applicationId: "app-003",
    officerId: "o1",
    officerName: "Anna Weber",
    queue: "Germany Work Permits",
    priority: "medium",
    assignedAt: "2024-06-18T10:00:00Z",
    dueDate: "2024-07-02T17:00:00Z",
    status: "active",
  },
];

export const MOCK_CASE_NOTES: CaseNote[] = [
  {
    id: "cn-001",
    applicationId: "app-001",
    authorId: "o1",
    authorName: "Anna Weber",
    authorRole: "case_officer",
    content:
      "Passport and degree verified. Employment contract under review — salary clause needs confirmation against Skilled Worker Act threshold.",
    internal: true,
    createdAt: "2024-06-05T11:45:00Z",
  },
  {
    id: "cn-002",
    applicationId: "app-001",
    authorId: "o1",
    authorName: "Anna Weber",
    authorRole: "case_officer",
    content:
      "Requested resubmission of biometric photo — background requirement not met.",
    internal: false,
    createdAt: "2024-06-05T12:00:00Z",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "al-001",
    actorId: "u1",
    actorEmail: "priya.sharma@email.com",
    actorRole: "applicant",
    action: "application.submitted",
    resource: "application",
    resourceId: "app-001",
    ipAddress: "203.0.113.42",
    userAgent: "Mozilla/5.0 Chrome/125.0",
    timestamp: "2024-06-01T10:00:00Z",
  },
  {
    id: "al-002",
    actorId: "o1",
    actorEmail: "anna.weber@avensaoverseas.com",
    actorRole: "case_officer",
    action: "application.status.changed",
    resource: "application",
    resourceId: "app-001",
    ipAddress: "198.51.100.10",
    userAgent: "Mozilla/5.0 Safari/17",
    timestamp: "2024-06-05T11:00:00Z",
    metadata: { from: "submitted", to: "document_review" },
  },
  {
    id: "al-003",
    actorId: "o1",
    actorEmail: "anna.weber@avensaoverseas.com",
    actorRole: "case_officer",
    action: "document.verification.completed",
    resource: "document",
    resourceId: "doc-001",
    ipAddress: "198.51.100.10",
    userAgent: "Mozilla/5.0 Safari/17",
    timestamp: "2024-06-05T11:00:00Z",
    metadata: { result: "accepted" },
  },
  {
    id: "al-004",
    actorId: "a1",
    actorEmail: "admin@avensaoverseas.com",
    actorRole: "super_admin",
    action: "rule.published",
    resource: "eligibility_rule",
    resourceId: "de-skilled-worker-rule-001",
    ipAddress: "192.0.2.1",
    userAgent: "Mozilla/5.0 Chrome/125.0",
    timestamp: "2024-01-15T09:00:00Z",
    metadata: { version: "2024.1" },
  },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: "art-001",
    title: "Germany's Skilled Immigration Act: What Changed in 2024",
    slug: "germany-skilled-immigration-act-2024",
    excerpt:
      "A comprehensive overview of the key amendments effective from 2024, including new salary thresholds and recognition pathways.",
    content:
      "Germany's updated Skilled Worker Immigration Act came into full effect in early 2024, introducing significant changes to how qualified professionals can move to Germany for work. Key changes include new salary thresholds for the EU Blue Card, simplified qualification recognition for certain professions, and introduction of the Opportunity Card for job seekers.\n\nReview your qualifications against the latest recognition requirements and ensure your salary meets the updated thresholds before applying.\n\nSource: Federal Ministry of the Interior and Community (BMI). Always verify requirements with official government sources.",
    category: "News",
    tags: ["Germany", "Work Visa", "Skilled Worker", "2024"],
    author: "Avensa Editorial Team",
    publishedAt: "2024-03-15T09:00:00Z",
    updatedAt: "2024-03-15T09:00:00Z",
    status: "published",
    countryIds: ["de"],
    routeIds: ["de-skilled-worker", "de-eu-blue-card"],
  },
  {
    id: "art-002",
    title: "Spain Digital Nomad Visa: Complete Guide 2024",
    slug: "spain-digital-nomad-visa-guide-2024",
    excerpt:
      "Eligibility, required documents, income thresholds and the full application process for Spain's Digital Nomad Visa.",
    content:
      "Spain's Digital Nomad Visa, introduced under the Start-Up Act, has become one of the most popular remote work visas in Europe. Applicants must prove remote work for foreign companies (max 20% Spanish income) and a minimum monthly income of approximately €2,646.\n\nSource: Spanish Ministry of Inclusion, Social Security and Migration. Information is for guidance only.",
    category: "Guide",
    tags: ["Spain", "Digital Nomad", "Remote Work", "2024"],
    author: "Avensa Editorial Team",
    publishedAt: "2024-04-10T09:00:00Z",
    updatedAt: "2024-04-10T09:00:00Z",
    status: "published",
    countryIds: ["es"],
    routeIds: ["es-digital-nomad"],
  },
  {
    id: "art-003",
    title: "Understanding the Schengen 90/180 Day Rule",
    slug: "schengen-90-180-day-rule-explained",
    excerpt:
      "Plain-language explanation of the Schengen short-stay rule, how days are counted, and common mistakes travellers make.",
    content:
      "The Schengen short-stay rule allows non-visa-required visitors to stay in the Schengen Area for up to 90 days within any 180-day rolling window. The window is rolling, not calendar-year based. All Schengen countries count collectively. Always verify your specific situation with the relevant border authority.",
    category: "Guide",
    tags: ["Schengen", "Short Stay", "Calculator", "Travel"],
    author: "Avensa Editorial Team",
    publishedAt: "2024-02-20T09:00:00Z",
    updatedAt: "2024-02-20T09:00:00Z",
    status: "published",
  },
  {
    id: "art-004",
    title: "Portugal D8 Digital Nomad Visa: Is It Right for You?",
    slug: "portugal-d8-digital-nomad-visa",
    excerpt:
      "Detailed look at Portugal's D8 visa for remote workers, including income requirements, application steps and NHR tax regime.",
    content:
      "The Portuguese D8 visa allows remote workers to live in Portugal while earning income from abroad. The income threshold is set at 4x the Portuguese minimum wage. Successful applicants may benefit from the Non-Habitual Resident (NHR) tax regime.\n\nSource: AIMA (Agency for Integration, Migration and Asylum). Verify current requirements at official sources.",
    category: "Guide",
    tags: ["Portugal", "Digital Nomad", "D8", "Remote Work"],
    author: "Avensa Editorial Team",
    publishedAt: "2024-05-01T09:00:00Z",
    updatedAt: "2024-05-01T09:00:00Z",
    status: "published",
    countryIds: ["pt"],
    routeIds: ["pt-d8-digital-nomad"],
  },
];

export const MOCK_FAQS: FAQ[] = [
  {
    id: "faq-001",
    question: "Is the eligibility result on this portal a legal guarantee?",
    answer:
      "No. The eligibility checker provides preliminary, informational guidance based on configured rules. All final immigration decisions are made by the competent national authority. Always consult official government sources and, where appropriate, a qualified immigration lawyer.",
    category: "General",
    order: 1,
    status: "active",
  },
  {
    id: "faq-002",
    question: "How long does it take to get a German Skilled Worker Visa?",
    answer:
      "Processing times typically range from 4 to 8 weeks from submission. Times vary based on consulate workload and application completeness. Always check the relevant German mission's website for current wait times.",
    category: "Germany",
    order: 2,
    status: "active",
    countryIds: ["de"],
  },
  {
    id: "faq-003",
    question: "What is the EU Blue Card?",
    answer:
      "The EU Blue Card is an EU-wide work and residence permit for highly qualified non-EU professionals. In Germany, applicants need a university degree and a job offer above the salary threshold. It offers a faster route to permanent residence.",
    category: "Work Visas",
    order: 3,
    status: "active",
  },
  {
    id: "faq-004",
    question: "Do I need a job offer for the German Job Seeker Visa?",
    answer:
      "No. The Job Seeker Visa allows entry for up to 6 months to search for work. You must have a recognised qualification and sufficient financial means.",
    category: "Germany",
    order: 4,
    status: "active",
    countryIds: ["de"],
  },
  {
    id: "faq-005",
    question: "How is the Schengen 90/180 rule calculated?",
    answer:
      "You may stay in the Schengen Area for a maximum of 90 days within any rolling 180-day window. The window moves daily — for any given day, look back 180 days and count days spent in the Schengen Area. Use our Short-Stay Calculator.",
    category: "Short Stay",
    order: 5,
    status: "active",
  },
  {
    id: "faq-006",
    question: "What file formats can I upload for documents?",
    answer:
      "Avensa Overseas accepts PDF, JPG, PNG, and DOCX files up to 10 MB per file. Scans should be clear, complete, and show all four corners of the original document.",
    category: "Documents",
    order: 6,
    status: "active",
  },
  {
    id: "faq-007",
    question: "How does Avensa Overseas handle my personal data?",
    answer:
      "Your personal data is processed in accordance with our Privacy Policy and applicable data protection law, including GDPR. Documents are stored encrypted at rest with access controlled by role and time-limited signed URLs. You can request access or deletion through your account settings.",
    category: "Privacy",
    order: 7,
    status: "active",
  },
  {
    id: "faq-008",
    question: "Can I track my application status in real time?",
    answer:
      "Yes. Your applicant dashboard shows the current status, a full timeline of status changes, pending actions, document requests, and appointment information. Email and in-app notifications keep you updated at each stage.",
    category: "Applications",
    order: 8,
    status: "active",
  },
];

export const MOCK_ANALYTICS = {
  applicationsByCountry: [
    { name: "Germany", value: 142 },
    { name: "Netherlands", value: 98 },
    { name: "France", value: 76 },
    { name: "Spain", value: 64 },
    { name: "Portugal", value: 52 },
    { name: "Sweden", value: 38 },
    { name: "Austria", value: 29 },
    { name: "Others", value: 41 },
  ],
  applicationsByRoute: [
    { name: "Skilled Worker", value: 118 },
    { name: "EU Blue Card", value: 94 },
    { name: "Student Visa", value: 82 },
    { name: "HSM (NL)", value: 71 },
    { name: "Digital Nomad", value: 65 },
    { name: "Family", value: 48 },
    { name: "Job Seeker", value: 37 },
    { name: "Other", value: 25 },
  ],
  monthlyApplications: [
    { name: "Jan", value: 45, secondary: 38 },
    { name: "Feb", value: 52, secondary: 44 },
    { name: "Mar", value: 68, secondary: 55 },
    { name: "Apr", value: 74, secondary: 61 },
    { name: "May", value: 83, secondary: 70 },
    { name: "Jun", value: 91, secondary: 78 },
  ],
  metrics: [
    { label: "Total Applications", value: 540, change: 18.4, trend: "up" as const },
    { label: "Approved", value: 312, change: 12.1, trend: "up" as const },
    { label: "Pending Review", value: 124, change: -5.2, trend: "down" as const },
    { label: "Avg Processing Days", value: 22, change: -8.3, trend: "down" as const },
  ],
};
